version: '3'
services:

  product-api:
    build: './'
    container_name: product-api
    environment:
      - PORT=8080
    ports:
      - 8080:8080

  product-db:
    image: postgres:11
    container_name: product-db
    restart: always
    environment:
      - POSTGRES_DB=product-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5434:5432